language: ko-KR

early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  sequence_diagrams: true
  suggested_reviewers: false
  poem: false
  review_status: true
  collapse_walkthrough: false

  path_filters:
    - "!**/swagger.json"
    - "!**/README.md"

  path_instructions:
    # — SQL files (existing)
    - path: "**/*.sql"
      instructions: >
        As a team convention, we do not specify FK constraints. Please avoid suggesting adding FK constraints in code reviews.
        Although this is a TypeScript file, DDL statements modifying table structures are embedded as strings.
        For columns used as primary keys (PK) or foreign keys (FK), the column type must be specified as "bigint".
        If a column name is "id" or ends with "_id", verify that its SQL type is "bigint"; otherwise, emit a high-severity warning prefixed with “🚨🚨🚨”.

    - path: "**/*.java"
      instructions: >
        This project follows key rules from the NAVER Campus Hackday Java Coding Conventions (partial summary below; see full spec for details).
        * Indentation: use spaces (no tabs), tab width = 4 spaces. Files must end with Unix LF newline.
        * Line length: maximum 120 characters.
        * Imports: single-class imports only, allow wildcard for static imports, group imports with blank lines between sections.
        * Assignment operators (`=`, `+=`, `-=`, etc.): always have one space before and after; when breaking lines, the operator must start the next line (Binary expressions: operation sign on next line).
        * Lambda expressions: omit parentheses for a single parameter; surround `->` with spaces (`param -> expression`); use braces and explicit `return` for multi-statement bodies; choose short, clear parameter names to keep intent visible.
        For the complete set of conventions and detailed examples, please refer to the full spec at `https://naver.github.io/hackday-conventions-java/`.

  abort_on_close: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []

  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      disabled_rules:
        - EN_UNPAIRED_BRACKETS
        - EN_UNPAIRED_QUOTES
      disabled_categories:
        - TYPOS
        - TYPOGRAPHY
        - CASING
      enabled_only: false
      level: default
      enabled_rules: []
      enabled_categories: []
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    ast-grep:
      packages: []
      rule_dirs: []
      util_dirs: []
      essential_rules: true

chat:
  auto_reply: true

knowledge_base:
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
