services:
  postgres:
    image: postgres:17
    container_name: postgres-job_foreigner
    ports:
      - 52314:5432
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER_ID}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRES_DB: job_foreigner
    volumes:
      - ./docker-infra/data:/var/lib/postgresql/data
      - ./docker-infra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: redis-job_foreigner
    ports:
      - 52976:6379
    environment:
      TZ: Asia/Seoul
    labels:
      - "name=redis"
      - "mode=standalone"
