spring:
  config:
    activate:
      on-profile: dev
    import:
      - properties/application-database.yml
      - properties/application-security.yml
      - properties/application-mail.yml
      - properties/application-open-api.yml
      - properties/application-swagger.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${job-foreigner.postgres.url}
    username: ${job-foreigner.postgres.username}
    password: ${job-foreigner.postgres.password}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        hbm2ddl.auto: update
    open-in-view: false
  data:
    redis:
      host: ${job-foreigner.redis.host}
      port: ${job-foreigner.redis.port}
      repositories:
        enabled: false
  batch:
    jdbc:
      initialize-schema: always
  mail:
    host: ${job-foreigner.mail.host}
    port: ${job-foreigner.mail.port}
    username: ${job-foreigner.mail.username}
    password: ${job-foreigner.mail.password}
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 20000
          connectiontimeout: 20000
          writetimeout: 20000

springdoc:
  packagesToScan: kr.ac.kumoh.d138.JobForeigner
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    operations-sorter: alpha
    display-request-duration: true
    tags-sorter: alpha
  api-docs:
    groups:
      enabled: false
