spring:
  config:
    activate:
      on-profile: local
    import:
      - properties/application-database.yml
      - properties/application-security.yml
      - properties/application-mail.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${job-foreigner.local.postgres.url}
    username: ${job-foreigner.local.postgres.username}
    password: ${job-foreigner.local.postgres.password}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${job-foreigner.local.redis.host}
      port: ${job-foreigner.local.redis.port}
  mail:
    host: ${job-foreigner.local.mail.host}
    port: ${job-foreigner.local.mail.port}
    username: ${job-foreigner.local.mail.username}
    password: ${job-foreigner.local.mail.password}
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 15000
          writetimeout: 5000

logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdb.extract: trace
    org.hibernate.type.descriptor.sql: trace
springdoc:
  swagger-ui:
    operations-sorter: alpha  # 알파벳 순 정렬
    tags-sorter: alpha        # 태그 정렬 방식
    display-request-duration: true  # 요청 처리 시간 표시

